### ISSUE TITLE
Is this boilerplate also works with Foundation?

### ISSUE THREAD

**Issue by frappacchio** [CarloBernardi/bootstrap-boilerplate#1]
Hi, nice works!
Is this boilerplate also works with Foundation?

Thanks,
Francesco

**Comment by CarloBernardi** [comment]
Hi Francesco,
I'm glad to hear that you like the project!
I will provide a Foundation boilerplate as soon as possible.

Have a nice day!
Carlo

**Comment by CarloBernardi** [comment]
Hi Francesco,
Here you are: https://github.com/CarloBernardi/foundation-boilerplate

Could you kindly test both boilerplates?
Byee!!
